### PR TITLE
Added video title and thumbnail url extraction

### PR DESCRIPTION
**Pull request by inket**

### CODE REVIEW

**Comment by lilfaf** [comment]
Hi guys. Thank you for your contributions! Could you add support for meta extraction to the delegate based method also? I'll merge and bump a version with this in place. :wink:

**Comment by inket** [comment]
Sure! Also, I forgot a detail... merging this will make existent code using YTVimeoExtractor break because of the new parameters.

How about I remove the parameters I added here, and instead add new methods for getting all the information as a dictionary? That would be best I think.

**Comment by lilfaf** [comment]
You are right, we should try to keep backward compatibility. A dedicated method for metadata extraction is definitly better.

**Comment by lilfaf** [comment]
Merged df200d5319a5322f28f14f0e609b63f1a61ee1ce

**Pull request closed without merging**
